### PR TITLE
Escaping every variable in all scripts

### PR DESCRIPTION
**Pull request by mustaphazorgati**
Hey buddy.

Take 2.

The nerd in me was wondering what went wrong and I have hopefully fixed all issues.

Tested:

- [x] Backup without space in filename
- [x] Backup with space in filename
- [x] Clean file containing space
- [x] Clean file without space in filename
- [x] Restore zip file with space in filename (zip only containing db)
- [ ] Restore zip file without space in filename (zip only containing db)
- [ ] Restore db/config/attachment with space in filename
- [ ] Restore db/config/attachment without space in filename

### CODE REVIEW

**Comment by mustaphazorgati** [comment]
Honestly I don't care if we leave the file name restriction for `BACKUP_FILE_DATE_SUFFIX`. I just wanted to get this done so that we won't have funny stuff going off when we need any special character in anything.

**Comment by ttionya** [comment]
Thanks for the PR, I think it is necessary to enhance the robustness of the program.

Here are the issues I found yesterday and they have been fixed by you. It's great!

1. `for xx in "${RCLONE_DELETE_LIST[@]}"` is not working
2. backing up sqlite with `".backup ${BACKUP_FILE_DB}"`
3. zip compression with file selection `zip -jP ${ZIP_PASSWORD} ${BACKUP_FILE_ZIP} ${BACKUP_DIR}/*`
4. I confirm that there is a corresponding problem when restoring

About `BACKUP_FILE_DATE_SUFFIX` I think limiting the characters is more in line with common file naming. So I'm not going to change it. But I will test if the program works properly when the space character is allowed.

Finally I'm sorry for my bad English, I can only communicate with you through Google Translate.

**Comment by mustaphazorgati** [comment]
I am glad I can help. 

This is by far the best repo I found for backing up my passwords :)

Plus you respond very quick. I like working with you!

> But I will test if the program works properly when the space character is allowed.

If you find anything let me know. 

> Finally I'm sorry for my bad English, I can only communicate with you through Google Translate.

Don't worry. I can understand you fine. Hopefully you understand me too ^^

**Comment by mustaphazorgati** [comment]
Hey @ttionya!
I think I found an issue:
```
backup_1      | send-mail: applet not found
```
I see this message in the logs. Mail is still getting send out. I am not sure if this existed before upgrading to bash. 
An easy fix would be to install postfix.

**Comment by mustaphazorgati** [comment]
I found the issue. I have escaped the `MAIL_DEBUG` variable which leads to an empty parameter which is passed to `mailx` when debug is not enabled

**Pull request merged**
